# Generated by Django 5.2.1 on 2025-06-30 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاســـم')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهـاتف')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنـــوان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظــات')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العدسة')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الشركة (اختياري)')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء من الشركة')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع للعميل')),
                ('lens_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع العدسة (اختياري)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='بداية الشهر')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مغلق')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('previous_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ربح مرحل')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اســم المنتج')),
                ('category', models.CharField(choices=[('نظارة طبية', 'نظارة طبية'), ('نظارة شمسية', 'نظارة شمسية'), ('إكسسوارات', 'إكسسوارات')], max_length=20, verbose_name='الفـئة')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='العلامة التجارية')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الشراء')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية في المخزن')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='الباركود')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفاتورة')),
                ('sale_type', models.CharField(choices=[('قطاعي', 'قطاعي'), ('جملة', 'جملة')], default='قطاعي', max_length=10, verbose_name='نوع الفاتورة ')),
                ('payment_method', models.CharField(choices=[('نقدًا', 'نقدًا'), ('فيزا', 'فيزا'), ('آجل', 'آجل')], max_length=20, verbose_name='طريقة الدفع')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='الخصم')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='العميل')),
                ('monthly_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.monthlysession')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice', verbose_name='الفاتورة')),
                ('lens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lens', verbose_name='العدسـات')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر فاتورة',
                'verbose_name_plural': 'عناصر الفواتير',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
        migrations.AddField(
            model_name='monthlysession',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
        migrations.AddField(
            model_name='lens',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('category', models.CharField(choices=[('rent', 'إيجار'), ('salary', 'رواتب'), ('credit', 'سلفة'), ('purchases', 'مشتريات'), ('maintenance', 'صيانة'), ('electricity', 'كهرباء'), ('other', 'أخرى')], max_length=50, verbose_name='الفئة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('monthly_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.monthlysession')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysession',
            unique_together={('month', 'shop')},
        ),
    ]
