# Generated by Django 5.2.1 on 2025-06-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount_paid',
        ),
    ]
