# Generated by Django 5.2.1 on 2025-07-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='lens',
        ),
        migrations.DeleteModel(
            name='Lens',
        ),
    ]
