# Generated by Django 5.2.1 on 2025-06-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_invoice_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysession',
            name='month',
            field=models.DateField(verbose_name='بداية الشهر'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysession',
            unique_together={('month', 'shop')},
        ),
    ]
