# Generated by Django 5.2.1 on 2025-07-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_invoiceitem_lens_delete_lens'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم البند/العدسات'),
        ),
    ]
