# Generated by Django 5.2.1 on 2025-05-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_monthlysession_expense_monthly_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المدفوع'),
        ),
    ]
